---

- name: update homebrew and upgrade everything
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: install some brew packages
  homebrew:
    state: present
    name:
      - adns
      - ansible
      - aspell
      - autoconf
      - autopep8
      - bash
      - bash-completion
      - bash-git-prompt
      - cairo
      - composer
      - coreutils
      - curl
      - direnv
      - docbook
      - docbook-xsl
      - docker-machine
      - docker-machine-driver-xhyve
      - doctl
      - fd
      - fluxctl
      - fontconfig
      - fping
      - freetype
      - fribidi
      - fzf
      - gdbm
      - gdk-pixbuf
      - gettext
      - ghostscript
      - glances
      - glib
      - glow
      - gmp
      - gnu-getopt
      - gnupg
      - gnutls
      - go
      - gobject-introspection
      - googler
      - gpgme
      - graphite2
      - grc
      - grep
      - harfbuzz
      - helm
      - htop
      - httpie
      - hub
      - hyperkit
      - icu4c
      - ilmbase
      - imagemagick
      - irssi
      - jpeg
      - jq
      - k3d
      - k9s
      - krb5
      - kube-ps1
      - kubectx
      - kubernetes-cli
      - lastpass-cli
      - libassuan
      - libde265
      - libev
      - libevent
      - libffi
      - libgcrypt
      - libgpg-error
      - libheif
      - libiconv
      - libidn2
      - libksba
      - liblqr
      - libomp
      - libpng
      - librsvg
      - libtasn1
      - libtiff
      - libtool
      - libunistring
      - libusb
      - libyaml
      - links
      - little-cms2
      - lua
      - lzo
      - mackup
      - minikube
      - mutt
      - ncurses
      - neofetch
      - nettle
      - nmap
      - npth
      - oniguruma
      - openexr
      - openjpeg
      - openssl@1.1
      - p11-kit
      - packer
      - pandoc
      - pango
      - pcre
      - perl
      - pinentry
      - pixman
      - pkg-config
      - postgresql
      - powerlevel9k
      - pyenv
      - pyenv-virtualenv
      - python@2
      - python@3.8
      - rbenv
      - readline
      - reattach-to-user-namespace
      - ruby
      - ruby-build
      - screenresolution
      - shared-mime-info
      - speedtest-cli
      - sqlite
      - ssh-askpass
      - sshfs
      - stern
      - telnet
      - the_silver_searcher
      - tig
      - tmux
      - tokyo-cabinet
      - tree
      - unbound
      - utf8proc
      - webp
      - weechat
      - wget
      - x265
      - xhyve
      - xmlto
      - xz
      - yq
      - zsh
      - zsh-syntax-highlighting

- name: install some cask packages
  homebrew_cask:
    state: present
    name:
      - balenaetcher
      - caffeine
      - chromedriver
      - element
      - font-hack-nerd-font
      - google-chrome
      - keybase
      - lens
      - minikube
      - multipass
      - sabnzbd
      - tuntap
      - vagrant
      - vagrant-manager
      - vlc
      - wkhtmltopdf
